# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    apt:
      repo: puppetlabs/apt
      ref: 9.1.0
    alternatives:
      repo: puppet/alternatives
      ref: 5.0.0
    apache:
      repo: puppetlabs/apache
      ref: 10.1.1
    archive:
      repo: puppet/archive
      ref: 7.0.0
    augeas_core:
      repo: puppetlabs/augeas_core
      puppet_version: ">= 6.0.0"
    chrony:
      repo: puppet/chrony
      ref: 3.0.0
    concat:
      repo: puppetlabs/concat
      ref: 7.3.3
    cron:
      repo: puppet/cron
      ref: 3.0.0
    cron_core:
      repo: puppetlabs/cron_core
      puppet_version: ">= 6.0.0"
    datacat:
      repo: richardc/datacat
      ref: 0.6.2
    dockerinstall:
      repo: aursu/dockerinstall
      ref: 0.13.5
    graylog:
      repo: graylog/graylog
      ref: 1.0.0
    host_core:
      repo: puppetlabs/host_core
      puppet_version: ">= 6.0.0"
    inifile:
      repo: puppetlabs/inifile
      ref: 6.1.0
    java:
      repo: puppetlabs/java
      ref: 10.1.1
    logrotate:
      repo: puppet/logrotate
      ref: 6.1.0
    monit:
      repo: soli/monit
      ref: 3.0.0
    mount_core:
      repo: puppetlabs/mount_core
      puppet_version: ">= 6.0.0"
    nodejs:
      repo: puppet/nodejs
      ref: 9.0.1
    ntp:
      repo: puppetlabs/ntp
      ref: 10.1.0
    postfix:
      repo: puppet/postfix
      ref: 4.2.1
    postgresql:
      repo: puppetlabs/postgresql
      ref: 9.1.0
    puppet:
      repo: aursu/puppet
      ref: 0.7.1
    puppetdb:
      repo: puppetlabs/puppetdb
      ref: 7.13.0
    r10k:
      repo: puppet/r10k
      ref: 11.0.1
    selinux:
      repo: puppet/selinux
      ref: 4.0.0
    selinux_core:
      repo: puppetlabs/selinux_core
      puppet_version: ">= 6.0.0"
    stdlib:
      repo: puppetlabs/stdlib
      ref: 9.2.0
    sysctl:
      repo: thias/sysctl
      ref: 1.0.7
    systemd:
      repo: puppet/systemd
      ref: 5.2.0
    tlsinfo:
      repo: aursu/tlsinfo
      ref: 0.3.7
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
      puppet_version: ">= 6.0.0"
  repositories:
    grayloginstall:
      repo: https://github.com/aursu/puppet-grayloginstall.git
    mongodb:
      repo: https://github.com/voxpupuli/puppet-mongodb.git
    networksetup:
      repo: https://github.com/aursu/puppet-networksetup.git
      ref: tags/v1.5.2
    nginx:
      repo: https://github.com/aursu/puppet-nginx.git
      ref: tags/v4.4.1-rc0.2
    rlimits:
      repo: https://github.com/aursu/puppet-rlimits.git
