# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    alternatives:
      repo: puppet/alternatives
      ref: 3.0.0
    apache:
      repo: "puppetlabs/apache"
      ref: "5.5.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "6.2.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "4.2.0"
    postfix:
      repo: camptocamp/postfix
      ref: 1.10.0
    selinux:
      repo: "puppet/selinux"
      ref: "3.2.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "6.3.0"
    sysctl:
      repo: "thias/sysctl"
      ref: "1.0.6"
  repositories:
    augeas_core:
      repo: https://github.com/puppetlabs/puppetlabs-augeas_core.git
      puppet_version: ">= 6.0.0"
    nginx:
      repo: "https://github.com/aursu/puppet-nginx.git"
      ref: "tags/v1.1.1-rc0.5"
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      ref: "tags/1.0.7"
      puppet_version: ">= 6.0.0"


