# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    alternatives:
      repo: puppet/alternatives
      ref: 3.0.0
    apache:
      repo: puppetlabs/apache
      ref: 5.5.0
    archive:
      repo: puppet/archive
      ref: 4.5.0
    chrony:
      repo: aboe/chrony
      ref: 0.3.2
    concat:
      repo: puppetlabs/concat
      ref: 6.2.0
    cron:
      repo: puppet/cron
      ref: 2.0.0
    datacat:
      repo: richardc/datacat
      ref: 0.6.2
    elastic_stack:
      repo: elastic/elastic_stack
      ref: 7.0.0
    elasticsearch:
      repo: elastic/elasticsearch
      ref: 6.4.0
    graylog:
      repo: graylog/graylog
      ref: 0.9.0
    inifile:
      repo: puppetlabs/inifile
      ref: 4.2.0
    java:
      repo: puppetlabs/java
      ref: 6.3.0
    logrotate:
      repo: puppet/logrotate
      ref: 5.0.0
    mongodb:
      repo: puppet/mongodb
      ref: 3.1.0
    monit:
      repo: soli/monit
      ref: 3.0.0
    ntp:
      repo: puppetlabs/ntp
      ref: 8.3.0
    postfix:
      repo: camptocamp/postfix
      ref: 1.10.0
    postgresql:
      repo: puppetlabs/postgresql
      ref: 6.6.0
    selinux:
      repo: puppet/selinux
      ref: 3.2.0
    stdlib:
      repo: puppetlabs/stdlib
      ref: 6.3.0
    sysctl:
      repo: thias/sysctl
      ref: 1.0.6
    systemd:
      repo: camptocamp/systemd
      ref: 2.9.0
  repositories:
    augeas_core:
      repo: https://github.com/puppetlabs/puppetlabs-augeas_core.git
      puppet_version: ">= 6.0.0"
    dockerinstall:
      repo: https://github.com/aursu/puppet-dockerinstall.git
    grayloginstall:
      repo: https://github.com/aursu/puppet-grayloginstall.git
    mount_core:
      repo: https://github.com/puppetlabs/puppetlabs-mount_core.git
      puppet_version: ">= 6.0.0"
    nginx:
      repo: https://github.com/aursu/puppet-nginx.git
      ref: tags/v2.0.1-rc0.4
    rlimits:
      repo: https://github.com/aursu/puppet-rlimits.git
    selinux_core:
      repo: https://github.com/puppetlabs/puppetlabs-selinux_core.git
      puppet_version: ">= 6.0.0"
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"


