# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    apache:
      repo: "puppetlabs/apache"
      ref: "5.5.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "6.2.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "4.2.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "6.3.0"
  repositories:
    nginx:
      repo: "https://github.com/aursu/puppet-nginx.git"
      ref: "tags/v1.1.1-rc0.5"
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      ref: "tags/1.0.7"
      puppet_version: ">= 6.0.0"


