# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    apt:
      repo: puppetlabs/apt
      ref: 10.0.1
    alternatives:
      repo: puppet/alternatives
      ref: 5.0.0
    apache:
      repo: puppetlabs/apache
      ref: 11.1.0
    archive:
      repo: puppet/archive
      ref: 7.1.0
    augeas_core:
      repo: puppetlabs/augeas_core
    bsys:
      repo: aursu/bsys
      ref: 0.11.3
    chrony:
      repo: puppet/chrony
      ref: 3.0.0
    concat:
      repo: puppetlabs/concat
      ref: 9.0.2
    cron:
      repo: puppet/cron
      ref: 4.2.0
    cron_core:
      repo: puppetlabs/cron_core
    datacat:
      repo: richardc/datacat
      ref: 0.6.2
    dockerinstall:
      repo: aursu/dockerinstall
      ref: 0.23.3
    gitlab:
      repo: puppet/gitlab
      ref: 10.3.0
    gitlabinstall:
      repo: aursu/gitlabinstall
      ref: 1.17.0
    host_core:
      repo: puppetlabs/host_core
    inifile:
      repo: puppetlabs/inifile
      ref: 6.1.1
    logrotate:
      repo: puppet/logrotate
      ref: 7.1.0
    lsys_nginx:
      repo: aursu/lsys_nginx
      ref: 0.48.0
    lsys_postgresql:
      repo: aursu/lsys_postgresql
      ref: 0.53.1
    mongodb:
      repo: puppet/mongodb
      ref: 6.0.1
    mount_core:
      repo: puppetlabs/mount_core
    mysql:
      repo: puppetlabs/mysql
      ref: 16.2.0
    nginx:
      repo: aursu/nginx
      ref: 6.0.2
    nodejs:
      repo: puppet/nodejs
      ref: 11.0.0
    ntp:
      repo: puppetlabs/ntp
      ref: 10.1.0
    postfix:
      repo: puppet/postfix
      ref: 5.0.0
    postgresql:
      repo: puppetlabs/postgresql
      ref: 10.5.0
    puppet:
      repo: aursu/puppet
      ref: 0.22.5
    puppetdb:
      repo: puppetlabs/puppetdb
      ref: 7.13.0
    r10k:
      repo: puppet/r10k
      ref: 12.1.1
    selinux:
      repo: puppet/selinux
      ref: 4.0.0
    selinux_core:
      repo: puppetlabs/selinux_core
    stdlib:
      repo: puppetlabs/stdlib
      ref: 9.6.0
    sysctl:
      repo: thias/sysctl
      ref: 1.0.8
    systemd:
      repo: puppet/systemd
      ref: 6.6.0
    tlsinfo:
      repo: aursu/tlsinfo
      ref: 0.3.7
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
  repositories:
    networksetup:
      repo: https://github.com/aursu/puppet-networksetup.git
      ref: tags/v1.5.2
    rlimits:
      repo: https://github.com/aursu/puppet-rlimits.git
