services:
  rocky8puppet8bolt:
    build:
      context: .
      dockerfile: tests/redhat/Dockerfile
      args:
        osrepo: aursu/rockylinux
        os: $RL8
        osmajor: 8
        platform: puppet8
    privileged: true
    cap_add:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    user: root
    image: "aursu/rockylinux:${RL8TAG}-puppet8-bolt"
  rocky9puppet8bolt:
    build:
      context: .
      dockerfile: tests/redhat/Dockerfile
      args:
        osrepo: aursu/rockylinux
        os: $RL9
        osmajor: 9
        platform: puppet8
    privileged: true
    cap_add:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    user: root
    image: "aursu/rockylinux:${RL9TAG}-puppet8-bolt"
  ubuntu22puppet8bolt:
    build:
      context: .
      dockerfile: tests/ubuntu/Dockerfile
      args:
        os: $U22
        codename: $U22CODE
        platform: puppet8
    privileged: true
    cap_add:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    user: root
    image: "aursu/ubuntu:${U22TAG}-puppet8-bolt"
